### ISSUE TITLE
Incomplete Casts Still Saved as Drafts

### ISSUE THREAD

**Issue by rbanker** [UNICEF-Youth-Section/Locast-Android#9]
A new cast with no data is still saved as a draft.  There is code at CastEdit.java:339 that checks the cast and should delete it if not complete, but it does not currently do anything.

**Comment by asterite** [comment]
It works, but the code assumes a draft is something with any of the fields known. So, if the location is known but there's no title and no media, a draft will be saved. I think that the title is required, otherwise you end up with an empty entry in the casts. So I changed it to:

```
if (mTitleView.getText().length() == 0) {
  // delete the draft...
}
```

Let me know if the code should be something else.
